### ISSUE TITLE
Markdown not being displayed in collapsed issue

### ISSUE THREAD

**Issue by stuartlynn** [openjournals/theoj#151]

**Comment by marcrohloff** [comment]
I disabled markdown in collapsed issues because, if your markdown contains any kind of block elemnts, including headers, images, code blocks, lists or mathjax, it will be cut off and not display properly. Although I didn't test it I suspect the ellipses won't rok correctly either.

The currently implemented code actually does allow a limited sub-set of markdown like italic, bold, strike-out and inline-code (although you cannot see the bold because the default styling is bold)

**Comment by marcrohloff** [comment]
Can we close this?

**Comment by freelanceastro** [comment]
Yes.
