### ISSUE TITLE
Some new designs

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#215]
![oj-papers](https://cloud.githubusercontent.com/assets/4483/8274137/2bd657c0-1850-11e5-8ebb-1e68ee0032d5.png)
![oj-preview](https://cloud.githubusercontent.com/assets/4483/8274138/2bde3a44-1850-11e5-8669-435666d8c0ae.png)
![oj-reviewing](https://cloud.githubusercontent.com/assets/4483/8274139/2be33e36-1850-11e5-93e9-4507b68d4aa9.png)
![oj-submit](https://cloud.githubusercontent.com/assets/4483/8274140/2beb8dc0-1850-11e5-948d-7c97dd770c7e.png)

Also, a good point from David about consistency (or lack of if) in language:

> I don't know what the correct terms should be, but one thing I noticed is that there's potential opportunity to tighten up the consistency of terminology— e.g. you click on the tab "Your Papers" but the page header is "Your Submissions"; in the reviewing interface, you add "comments", but in the papers list, they're called "issues".

/ cc @marcrohloff @freelanceastro

**Comment by davidmill** [comment]
@arfon here's some styles to help things along a bit. Let me know if you need any clarification!

**HEADER**

.header_background {
  background-color: rgb(51, 85, 117);
  box-shadow: 0px 5px 10px 0px rgba(0, 0, 0, 0.2);
  height: 130px;
}

.username {
  font-size: 14px;
  font-family: "Montserrat";
  color: rgb(255, 255, 255);
  line-height: 20;
}


button text {
  font-size: 14px;
  font-family: "Montserrat";
  color: rgb(255, 255, 255);
  line-height: 28;
  text-align: center;
}

sign-out button {
  border-width: 2px solid rgb(77, 118, 156);
  border-radius: 5px;
  background-color: rgb(51, 85, 117);
  box-shadow: 0px 2px 0px 0px rgba(45, 74, 102, 0.004);
}

sign-out button hover {
  border: 2px solid rgb(184, 204, 223);
  border-radius: 5px;
  background-color: rgb(51, 85, 117);
  box-shadow: 0px 2px 0px 0px rgba(45, 74, 102, 0.1);
}

sign-out button active {
  border-radius: 5px;
  background-color: rgb(37, 62, 86);
  border: none;
}

**MY PAPERS**

~35px between paper info and horizontal rules

Title {
  font-size: 18px;
  font-family: "Montserrat";
  color: rgb(0, 0, 0);
  font-weight: 700;
  line-height: 24px;
}

submitted {
  font-size: 12px;
  font-family: "Montserrat";
  color: rgb(125, 125, 125);
  line-height: 18px;
  font-weight: 400;
}

submitted name/date/comment # {
  font-size: 12px;
  font-family: "Montserrat";
  color: rgb(81, 81, 81);
  line-height: 18px;
  font-weight: 700;
}

hr (or border-bottom?) {
1 px solid #c2c2c2
}


**PREVIEW**

Paper title {
  font-size: 26px;
  font-family: "Montserrat";
  color: rgb(0, 0, 0);
  font-weight: 700;
  line-height: 30;
 }

Authors {
  font-size: 14px;
  line-height: 20px
  font-family: "Montserrat";
  font-weight: 400;
  color: rgb(154, 154, 154);
  }

abstract {
  font-size: 12px;
  line-height: 18px
  font-weight: 400;
  font-family: "Montserrat";
  color: rgb(61, 61, 61);
}

submit button {
  font-size: 14px;
  font-family: "Montserrat";
  color: rgb(51, 85, 117);
  text-align: center;
  width: 110px;
  height: 35px;
  border-style: 2px solid rgb(51, 85, 117);
  border-radius: 5px;
  background-color: rgb(255, 255, 255);
  box-shadow: 0px 2px 0px 0px rgba(218, 218, 218, 0.1);
}

submit button hover {
  font-size: 14px;
  font-family: "Montserrat";
  color: rgb(255, 255, 255);
  text-align: center;
  width: 110px;
  height: 35px;
  border-style: 2px solid rgb(51, 85, 117);
  border-radius: 5px;
  background-color: rgb(51, 85, 117);
  box-shadow: 0px 2px 0px 0px rgba(218, 218, 218, 0.1);
}

submit button active {
  font-size: 14px;
  font-family: "Montserrat";
  color: rgb(255, 255, 255);
  text-align: center;
  width: 110px;
  height: 35px;
  border-style: 2px solid rgb(51, 85, 117);
  border-radius: 5px;
  background-color: rgb(51, 85, 117);
}


**REVIEWING**

green {
  background-color: rgb(182, 214, 31);
}

red{
  background-color: rgb(233, 0, 66);
}

white comment buttons {
  font-size: 10px;
  font-family: "Montserrat";
  color: rgb(154, 154, 154);
  line-height: 20;
  text-align: center;
  border-style: 1px solid (154, 154, 154);
  border-radius: 5px;
  background-color: rgb(255, 255, 255);
  box-shadow: 0px 4px 0px 0px rgba(218, 218, 218, 0.1);
}

white comment buttons hover {
  font-size: 10px;
  font-family: "Montserrat";
  color: rgb(120, 120, 120);
  line-height: 20;
  text-align: center;
  border-style: 1px solid (120, 120, 120);
  border-radius: 5px;
  background-color: rgb(255, 255, 255);
  box-shadow: 0px 4px 0px 0px rgba(218, 218, 218, 0.1);
}

white comment buttons active {
  font-size: 10px;
  font-family: "Montserrat";
  color: rgb(120, 120, 120);
  line-height: 20;
  text-align: center;
  border-style: 1px solid (120, 120, 120);
  border-radius: 5px;
  background-color: rgb(255, 255, 255);
}

grey background throughout {
  background-color: rgb(230, 230, 230);
}

**Comment by marcrohloff** [comment]
Thanks David. Those look much, much better.

I had some questions.

For the preview page what is the intent of the black section between the rendered pdf pages on the left and the pane on the right with the submit button? Is that statically positioned or should it scroll with the pages?

I had some concerns about the review page.
Currently document issues are aligned with the top of the document and other issues are aligned with their location in the paper when possible (i.e. I push overlapping issues down so that they don't overlap when collapsed). The more we put here the harder this gets. Although you only show 2 users in your mockup it is very easy to have more (an editor, submittor, collaboartor a couple of reviewers)

The same is true for buttons. Currently my worst case is two buttons at the same time but as we work out the kinks that might change as well. Also do we want to drop the coloring on the buttons? The one case is that the editor has an accept and reject button which are currently green and red respectively.

There are also some fields which we are now missing: the user's role on the paper, the current state of the paper and the number of open and closed issues (only when the paper is in the under review state). Are we OK with removing these?

**Comment by arfon** [comment]
Not sure how @davidmill has his GitHub notifications set up so mentioning him by name to trigger a (probable) email. :point_up:

**Comment by davidmill** [comment]
Thanks @arfon @marcrohloff! Responses inline:

For the preview page what is the intent of the black section between the rendered pdf pages on the left and the pane on the right with the submit button? Is that statically positioned or should it scroll with the pages?

-- That's just the current PDF scroller (default in Chrome, I believe, where I took the background screenshot)

I had some concerns about the review page.

Currently document issues are aligned with the top of the document and other issues are aligned with their location in the paper when possible (i.e. I push overlapping issues down so that they don't overlap when collapsed). The more we put here the harder this gets. Although you only show 2 users in your mockup it is very easy to have more (an editor, submittor, collaboartor a couple of reviewers)

-- The reason I made this change is because I think a user needs to quickly understand what those color labels mean, so having the "submitter" and "reviewer" labels in their respective color in closer proximity to the comments (which are also color coded based on who submitted the comment) seemed to make sense in terms of making a quick visual connection between the color label, role, and comment.

The same is true for buttons. Currently my worst case is two buttons at the same time but as we work out the kinks that might change as well. Also do we want to drop the coloring on the buttons? The one case is that the editor has an accept and reject button which are currently green and red respectively.

-- I'm not sure I follow this part (pretty new to the interface and I may not have come across some scenarios)

There are also some fields which we are now missing: the user's role on the paper, the current state of the paper and the number of open and closed issues (only when the paper is in the under review state). Are we OK with removing these?

-- The user role is indicated in the list of people on the right in the reviewing screen (I'm the user in this case—submitter—labeled green)
-- I think current state could go just to the left of the "check for updates" button
-- I'm not seeing where open/closed issues are in my view on the current beta—can someone screenshot?

**Comment by marcrohloff** [comment]
Here is a shot with the open/closed issue count
![screen shot 2015-06-22 at 9 25 36 pm](https://cloud.githubusercontent.com/assets/737058/8298392/77a3d7d8-1925-11e5-9577-e01e57ce4f87.png)

Here is one with the accept/reject buttons (only visible by the editor)
![screen shot 2015-06-22 at 9 47 21 pm](https://cloud.githubusercontent.com/assets/737058/8298618/51a9adf2-1928-11e5-9fac-b8c34ffef246.png)

And this is another one with delete and start review buttons (again only visible to the editor)
![screen shot 2015-06-22 at 9 39 17 pm](https://cloud.githubusercontent.com/assets/737058/8298540/2a945b8c-1927-11e5-82b0-d370bd46b173.png)

The last one is this one for reviewers
![screen shot 2015-06-22 at 9 42 45 pm](https://cloud.githubusercontent.com/assets/737058/8298590/c925d906-1927-11e5-929d-3d75c730e963.png)

But as I said I expect that we will land up with cases where there will be more buttons. (especially for editors)

**Comment by marcrohloff** [comment]
Also I'll probably drop the black scrollbar on the preview page. I'm not sure why it isn't like the review page (no scrollbar). It is just way too heavy.

**Comment by davidmill** [comment]
@marcrohloff got it, thank you for these! Thinking about this, and will drop some new designs ASAP.

**Comment by davidmill** [comment]
@marcrohloff sorry for the delay! A few questions:

- what's the functionality distinction between an editor and a reviewer?
- what is the selector field beside "Reviewer One"? Are reviewers anonymous? 
- is a "start reviewing" button required? Does the action of arriving at this page imply a person intends to start reviewing? Is there a time component?
- can "complete" and/or "delete" buttons appear at the bottom of the document or only appear when an editor/reviewer reaches the end of the paper / open issues?

**Comment by marcrohloff** [comment]
@davidhill I'm probably not the best person to answer this but here's my understanding:

* An editor is more of an oversight role. They assign reviewers and decide when the review is complete and if the paper is ready to publish. The reviewer is a knowledgeable person who looks at the paper for inconsistencies, etc.

* Reviewers are initially anonymous but can choose to make themselves public (through an 'Action' button). The editor, submittor and collaborators are always public. Additionally editors can always see the reviewers even when they are not public.
There are two things next to the reviewers name, (1) a uniquely coloured dot that matches the coloured bar to the left of each comment. (2) A read-only checkbox that indicates to the editor that the reviewer has marked their review as complete.

* I don't know if there is a way around this, though I agree it would be good if we could find a way to make it implicit. There is going to be some time between when a document is submitted, the first reviewer is added and the last reviewer is added. My current rule is that you cannot add (or more importantly delete) reviewers once a document is under review.
I guess that we could loosen this stricture and set the document to under-review when the first reviewer is added as well as allow adding and removing reviewers when the document is under review. We would need to add a rule to disallow deleting reviewers who have already made a comment.
@freelanceastro @arfon What do you think?

* "Can complete / delete buttons appear at the end of the document"?
Technically there is no reason. Do you think it is a good idea since documents can get quite long? I like things up front where people can see them.

**Comment by davidmill** [comment]
![oj-reviewing-v2](https://cloud.githubusercontent.com/assets/1163022/8632379/f89f75e0-275d-11e5-8271-2eaab944a930.jpg)

@marcrohloff this addresses some of the missing pieces and scaling issues (with buttons and contributors). 

The colored contributor/role labels could easy include the read-only checkbox within, it would just make that colored round rectangle a bit wider.

This mockup includes three buttons at the top (accept/reject/delete) but it could pretty easily accommodate four at once if necessary.

Is it necessary to prominently display closed issues? Is "reopening" an issue possible?

**Comment by marcrohloff** [comment]
Thanks. I won't be in much for the next couple of weeks but I'll do it when I can.

**Comment by arfon** [comment]
:sparkles: @davidmill. These are looking excellent. 

> Is it necessary to prominently display closed issues? Is "reopening" an issue possible?

I guess it's possible that someone could accidentally close an issue and want to re-open it but other than that I suspect not?

**Comment by marcrohloff** [comment]
We do currently allow re-opening an issue (The current options being
resolve, dispute, open)

**Comment by marcrohloff** [comment]
Would it make sense to move the username, search box and sign in/out links into the menu at the left? That way the layout will work better on a narrow mobile device (where the menu slides in and out)

**Comment by marcrohloff** [comment]
And as a follow up, how much time should I put into making the UI responsive? (Especially sinceannotation will never work well on a small screen)

**Comment by arfon** [comment]
> And as a follow up, how much time should I put into making the UI responsive? (Especially sinceannotation will never work well on a small screen)

I wouldn't focus much (if any) effort on this right now.

**Comment by arfon** [comment]
> Would it make sense to move the username, search box and sign in/out links into the menu at the left? 

@davidmill - what are your thoughts?

**Comment by marcrohloff** [comment]
I'm going to need a fallback for the Montserrat font. It doesn't exist on my Mac

**Comment by davidmill** [comment]
@marcrohloff https://www.google.com/fonts/specimen/Montserrat

**Comment by marcrohloff** [comment]
@davidmill I implemented the styling on everything except the review page. A lot of it I just had to guess from the screen shots so please review it and tell me what I should tweak. The montserrat font is very difficult, it is hard to distinguish between bold and normal fonts (as you can see in the left hand menu)

**Comment by davidmill** [comment]
@marcrohloff Just tagged you in the CSS thread above, which should help. The PSDs should give better insight than the screenshots, as well: https://www.dropbox.com/sh/gswsw6wqwco62yg/AABJ5EllrODfhYx9t2GAtySda?dl=0

I'm not tied to the Montserrat, but I do think it works well in most places, and at smaller size the contrast between the 400 and 600 weights are clear. It might be worth using a color change to indicate the active page in the menu if bolding is not sufficient.

**Comment by marcrohloff** [comment]
Having worked with this I think we need more width on the reviewer page for the list of submittors, editor and reviewers which take quite a bit of space. Maybe we should remove the 'add a comment to the paper' button and put it at the top left or right (or as a semi-transparent overlay across the top since it seems that Arxiv doesn't print stuff there)
![screen shot 2015-07-27 at 8 20 29 pm](https://cloud.githubusercontent.com/assets/737058/8922228/660d86a2-349d-11e5-842e-88ac4cdbc425.png)
 of the pdf.

**Comment by marcrohloff** [comment]
We could also assume that any comment added in the top 1/2 inch of the document is a document level comment.

**Comment by marcrohloff** [comment]
This should be done (apart from the fact that I think we need to increase the header width)

**Comment by arfon** [comment]
@davidmill - I've been fiddling with some of the CSS here and it's _really_ hard to get a 'light' version of the Montserrat font that matches your designs. As far as I can tell there's only a 400 and 700 weight version available and the 400 is definitely heavier-weight than what you have in your designs.

Do you think we might be able to find a different font with a better range in weights?

**Comment by marcrohloff** [comment]
Can we close this?
