### ISSUE TITLE
Status API should respond to arXiv ID

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#24]
...so that people don't have to know the SHA for the paper to use the embed URL.

**Comment by marcrohloff** [comment]
Would it make sense to remove SHA's completely and make all API and web URLs use the arxiv id like arxiv does?

**Comment by freelanceastro** [comment]
Probably a good idea, but not a priority at the moment.

**Comment by marcrohloff** [comment]
I just prefer to get public URLs right the first thing rather than changing them later and having to create redirects, etc to make sure that old url's are not valid.
My only concern might be if we decide to support back-ends other than the Arxiv so we might want to have a scheme like /paper/arxiv/{id} or /paper/arxiv-{id}

**Comment by freelanceastro** [comment]
Fair enough. And that's a reasonable concern and a good solution. I think /paper/arxiv/{id} is good.

**Comment by marcrohloff** [comment]
Fixed by #205. All URLs now accept the id in the format arxiv:1234.5678v9 or arxiv:1234.5678 (without the version) or just the internal id of the paper if you happen to know it.
