### ISSUE TITLE
Provide a LaTeX template?

### ISSUE THREAD

**Issue by jradavenport** [openjournals/theoj#258]
I can see the arguments for and against providing a LaTeX template, but it might be good to at least *suggest* a certain template or style for authors to submit using. This could go a long way towards making refereeing papers easier.

Side note:
Is there need for a "real" paper to test the entire workflow with? I have a short paper in prep that might be ideal for The Open Journal as a venue...

**Comment by arfon** [comment]
@freelanceastro - we have a template correct?

**Comment by freelanceastro** [comment]
We do, and there's a link to it on the About page. It's not perfect, but it gets the job done. If you've got any suggestions on how to make it better, that would be *really* awesome, because I just slapped it together very fast.

And yeah, @jradavenport, "real" papers would be great. The more the better. Submit yours and then tell all your friends to do the same. We want them all, now.

**Comment by jradavenport** [comment]
Great! I found a class file [here](https://github.com/openjournals/theoj/blob/master/public/downloads/openjournal.cls). Couldn't find any such link on http://theoj.org

I'll give it a shot!

**Comment by marcrohloff** [comment]
​You'd want to try this page http://astro.theoj.org/about
which links to this template
http://astro.theoj.org/downloads/openjournal.cls

**Comment by jradavenport** [comment]
:+1:
Didn't know about the astro subdomain! Excellent!
