### ISSUE TITLE
Establish CSS base styles

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#27]
Currently we're doing lots of weird stuff between blocks like these in each template.

```
<style>
</style>
```

We're also doing this like [this](https://github.com/openjournals/theoj/commit/8547054e437cd196242b0f8f3f6118b1fcf0ce7f#commitcomment-9409942)

Basically I'd like us to define some base classes (presumably inheriting from Polymer classes) that relate to things we are going to reuse.

**Comment by marcrohloff** [comment]
Arfonm could you elaborate on this a bit?

**Comment by arfon** [comment]
Sure thing. Currently we're doing things like this: https://github.com/openjournals/theoj/blob/8547054e437cd196242b0f8f3f6118b1fcf0ce7f/app/assets/components/oj-paper-collection.html#L18-L33

It's not clear to me why these view components have so much CSS in them - I'd expect them to be in SASS/SCSS stylesheets rather than here. I may be wrong though - perhaps @stuartlynn has some ideas about what's best practice here.

**Comment by stuartlynn** [comment]
Polymer components are supposed to be mostly self contained, so that they can be dropped on to a page and just work, This means having some default styles which can be overridden in another style sheet. I am happy moving these to a global stylesheet but actually quite like them being in the component, keeps all the code for that particular part of the app in the one place. 




Don’t have massively strong feelings either way. The only thing we need to watch is that the shadow dom specific css selectors only work natively in chrome. There is a web components polyfill for everything else but it  requires the style sheet to have a shadow-dom-shim property. If we move them to a separate file then we just need to make sure that when we include it, it has that property. 


—

**Comment by arfon** [comment]
OK, I'll shut up about this :smile:

**Comment by marcrohloff** [comment]
I''m guessing that one advantage to having them here is that they are is that they are namespaced to this component (and not every element in the app that has an 'item' class for example).

I'll keep an eye out for anything that looks like it should moved into a global stylesheet.

**Comment by arfon** [comment]
> I'll keep an eye out for anything that looks like it should moved into a global stylesheet.

:+1:
